version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      ignore:
          - update-types: ["version-update:semver-major", "version-update:semver-minor"]
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
      ignore:
          - update-types: ["version-update:semver-major", "version-update:semver-minor"]
