const list3k = {
	points: 3000,
	list_name: "Tank Company",
	list_id: "INxmTZKLK2ZBukd9Lv631",
	user_id: "RAdote3fY4fhXCuFzqpOjjvOqfa2",
	main_faction: "Solar Auxillia",
	allegiance: "Neutral",
	formations: [
		{
			id: 2001,
			name: "Solar Auxilia Armoured Company",
			faction: "Solar Auxillia",
			allegiance: "Neutral",
			compulsory: [
				{
					id: 2005,
					type: "Battle Tank",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJcompulsorySlot0",
					selected_unit: {
						id: 2008,
						name: "Leman Russ Strike Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Battle Tank",
						base_cost: 175,
						base_size: 4,
						max_size: 10,
						main_unit: [2008],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Leman Russ battlecannon or Vanquisher battlecannon",
									"Hull Mounted heavy bolter or Hull Mounted lascannon",
								],
							},
						],
						upgrade_options: [{ name: "Additional Leman Russ", number: 0, cost: 0, size: 0 }],
						datasheet_info: [
							{
								text: "A Leman Russ Strike Squadron can purchase the following upgrades:",
								options: [
									{ text: "2 additional Leman Russ", cost: 85 },
									{ text: "4 additional Leman Russ", cost: 160 },
									{ text: "6 additional Leman Russ", cost: 220 },
								],
							},
						],
					},
				},
				{
					id: 2005,
					type: "Battle Tank",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJcompulsorySlot1",
					selected_unit: {
						id: 2009,
						name: "Malcador Tank Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Battle Tank",
						base_cost: 165,
						base_size: 2,
						max_size: 6,
						main_unit: [2009],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Hull Mounted heavy bolter or Hull Mounted lascannon or Hull Mounted autocannon or Hull Mounted demolisher cannon",
									"Malcador battlecannon or Malcador Vanquisher battlecannon or Malcador lascannon turret",
									"Malcador heavy bolter sponsons or Malcador lascannon sponsons or Malcador autocannon sponsons",
								],
							},
						],
						upgrade_options: [{ name: "Additional Malcador", number: 1, cost: 70, size: 1 }],
						datasheet_info: [
							{
								text: "A Malcador Tank Squadron can purchase any of the following upgrades: The same upgrade may be taken more than once.",
								options: [
									{ text: "1 additional Malcador", cost: 70 },
									{ text: "2 additional Malcador", cost: 130 },
									{ text: "4 additional Malcador", cost: 240 },
								],
							},
						],
					},
				},
				{
					id: 2006,
					type: "Heavy Armour",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJcompulsorySlot2",
					selected_unit: {
						id: 2010,
						name: "Auxilia Super-Heavy Tank Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Heavy Armour",
						base_cost: 100,
						base_size: 1,
						max_size: 6,
						main_unit: [2010],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Hull Mounted demolisher cannon and Hull Mounted heavy bolter",
									"Baneblade cannon with Co-axial autocannon or Hellhammer cannon with Co-axial autocannon",
									"Baneblade heavy bolter sponsons or Baneblade autocannon sponsons or Baneblade heavy flamer sponsons",
									"Lascannon sponson turrets",
								],
							},
						],
						upgrade_options: [{ name: "Additional Super-heavy", number: 2, cost: 180, size: 2 }],
						datasheet_info: [
							{
								text: "An Auxilia Super-Heavy Tank Squadron can purchase any of the following upgrades: The same upgrade may be taken more than once.",
								options: [
									{ text: "1 additional Super-heavy", cost: 90 },
									{ text: "3 additional Super-heavy", cost: 255 },
									{ text: "5 additional Super-heavy", cost: 390 },
								],
							},
						],
					},
				},
				{
					id: 9004,
					type: "HQ",
					faction: "Solar Auxillia",
					restricted: true,
					options: [9003],
					description: "Tank Commander",
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJcompulsorySlot3",
					selected_unit: {
						id: 9003,
						name: "Tank Commander",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "HQ",
						unique: true,
						base_cost: 10,
						base_size: 1,
						max_size: 1,
						break_strength: 0,
						main_unit: [],
						related_unit: [],
						loadout: [],
						upgrade_options: [],
						datasheet_info: [],
					},
				},
			],
			optional: [
				{
					id: 2005,
					type: "Battle Tank",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJoptionalSlot0",
					selected_unit: {
						id: 2008,
						name: "Leman Russ Strike Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Battle Tank",
						base_cost: 175,
						base_size: 4,
						max_size: 10,
						main_unit: [2008],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Leman Russ battlecannon or Vanquisher battlecannon",
									"Hull Mounted heavy bolter or Hull Mounted lascannon",
								],
							},
						],
						upgrade_options: [{ name: "Additional Leman Russ", number: 0, cost: 0, size: 0 }],
						datasheet_info: [
							{
								text: "A Leman Russ Strike Squadron can purchase the following upgrades:",
								options: [
									{ text: "2 additional Leman Russ", cost: 85 },
									{ text: "4 additional Leman Russ", cost: 160 },
									{ text: "6 additional Leman Russ", cost: 220 },
								],
							},
						],
					},
				},
				{
					id: 2005,
					type: "Battle Tank",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJoptionalSlot1",
					selected_unit: {
						id: 2009,
						name: "Malcador Tank Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Battle Tank",
						base_cost: 165,
						base_size: 2,
						max_size: 6,
						main_unit: [2009],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Hull Mounted heavy bolter or Hull Mounted lascannon or Hull Mounted autocannon or Hull Mounted demolisher cannon",
									"Malcador battlecannon or Malcador Vanquisher battlecannon or Malcador lascannon turret",
									"Malcador heavy bolter sponsons or Malcador lascannon sponsons or Malcador autocannon sponsons",
								],
							},
						],
						upgrade_options: [{ name: "Additional Malcador", number: 1, cost: 70, size: 1 }],
						datasheet_info: [
							{
								text: "A Malcador Tank Squadron can purchase any of the following upgrades: The same upgrade may be taken more than once.",
								options: [
									{ text: "1 additional Malcador", cost: 70 },
									{ text: "2 additional Malcador", cost: 130 },
									{ text: "4 additional Malcador", cost: 240 },
								],
							},
						],
					},
				},
				{
					id: 2006,
					type: "Heavy Armour",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
					slot_ref: "formation5UfJ6TP2bt8vUAaartTeJoptionalSlot2",
					selected_unit: {
						id: 2010,
						name: "Auxilia Super-Heavy Tank Squadron",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Heavy Armour",
						base_cost: 100,
						base_size: 1,
						max_size: 6,
						main_unit: [2010],
						related_unit: [],
						loadout: [
							{
								text_option: [
									"Hull Mounted demolisher cannon and Hull Mounted heavy bolter",
									"Baneblade cannon with Co-axial autocannon or Hellhammer cannon with Co-axial autocannon",
									"Baneblade heavy bolter sponsons or Baneblade autocannon sponsons or Baneblade heavy flamer sponsons",
									"Lascannon sponson turrets",
								],
							},
						],
						upgrade_options: [{ name: "Additional Super-heavy", number: 2, cost: 180, size: 2 }],
						datasheet_info: [
							{
								text: "An Auxilia Super-Heavy Tank Squadron can purchase any of the following upgrades: The same upgrade may be taken more than once.",
								options: [
									{ text: "1 additional Super-heavy", cost: 90 },
									{ text: "3 additional Super-heavy", cost: 255 },
									{ text: "5 additional Super-heavy", cost: 390 },
								],
							},
						],
					},
				},
			],
			choice: [
				[
					{
						id: 2005,
						type: "Battle Tank",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
						slot_ref: "formation5UfJ6TP2bt8vUAaartTeJchoiceSlots00",
						selected_unit: {
							id: 2008,
							name: "Leman Russ Strike Squadron",
							faction: "Solar Auxillia",
							allegiance: "Neutral",
							detachment_type: "Battle Tank",
							base_cost: 175,
							base_size: 4,
							max_size: 10,
							main_unit: [2008],
							related_unit: [],
							loadout: [
								{
									text_option: [
										"Leman Russ battlecannon or Vanquisher battlecannon",
										"Hull Mounted heavy bolter or Hull Mounted lascannon",
									],
								},
							],
							upgrade_options: [{ name: "Additional Leman Russ", number: 0, cost: 0, size: 0 }],
							datasheet_info: [
								{
									text: "A Leman Russ Strike Squadron can purchase the following upgrades:",
									options: [
										{ text: "2 additional Leman Russ", cost: 85 },
										{ text: "4 additional Leman Russ", cost: 160 },
										{ text: "6 additional Leman Russ", cost: 220 },
									],
								},
							],
						},
					},
					{
						id: 2007,
						type: "Artillery",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
						slot_ref: "formation5UfJ6TP2bt8vUAaartTeJchoiceSlots01",
						selected_unit: null,
					},
					{
						id: 2008,
						type: "Air Support",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
						slot_ref: "formation5UfJ6TP2bt8vUAaartTeJchoiceSlots02",
						selected_unit: null,
					},
				],
			],
			ref_id: "formation5UfJ6TP2bt8vUAaartTeJ",
		},
		{
			id: 2000,
			name: "Solar Auxilia Sub-Cohort",
			faction: "Solar Auxillia",
			allegiance: "Neutral",
			compulsory: [
				{
					id: 2000,
					type: "HQ",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4compulsorySlot0",
					selected_unit: {
						id: 2000,
						name: "Legate Commander Detachment",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "HQ",
						base_cost: 16,
						base_size: 1,
						max_size: 1,
						main_unit: [2000],
						related_unit: [],
						loadout: [{ text_option: ["Archeotech pistol", "Volkite chargers"] }],
						upgrade_options: [],
						datasheet_info: [],
					},
				},
				{
					id: 2002,
					type: "Support",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4compulsorySlot1",
					selected_unit: {
						id: 2003,
						name: "Auxilia Ogryn Charonite Section",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Support",
						base_cost: 50,
						base_size: 4,
						max_size: 8,
						main_unit: [2004],
						related_unit: [],
						loadout: [{ text_option: ["Charonite claws"] }],
						upgrade_options: [{ name: "Additional Charonite Ogryn", number: 4, cost: 30, size: 4 }],
						datasheet_info: [
							{
								text: "An Auxilia Charonite Ogryn Section can purchase the following upgrades:",
								options: [
									{ text: "2 additional Charonite Ogryn", cost: 15 },
									{ text: "4 additional Charonite Ogryn", cost: 30 },
								],
							},
						],
					},
				},
				{
					id: 9003,
					type: "Core",
					faction: "Solar Auxillia",
					restricted: true,
					options: [2002],
					description: "Lasrifle detachment",
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4compulsorySlot2",
					selected_unit: {
						id: 2002,
						name: "Auxilia Lasrifle Tercio",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Core",
						base_cost: 30,
						base_size: 4,
						max_size: 16,
						main_unit: [2002],
						related_unit: [9000, 9001],
						loadout: [{ text_option: ["Auxillia lasrifles"] }],
						upgrade_options: [
							{ name: "Additional Auxiliaries", number: 4, cost: 24, size: 4 },
							{ name: "Additional Auxiliaries with Flamers", number: 0, cost: 0, size: 0 },
							{ name: "Additional Veletarii", number: 0, cost: 0, size: 0 },
							{ name: "Additional Charonite Ogryns", number: 0, cost: 0, size: 0 },
						],
						datasheet_info: [
							{
								text: "An Auxilia Lasrifle Tercio can purchase up to six upgrades. It may purchase the same upgrade multiple times: Each upgrade increases the Detachment size by 2.",
								options: [
									{ text: "Auxiliaries", cost: 12 },
									{ text: "Auxiliaries with Flamers", cost: 12 },
									{ text: "Veletarii", cost: 12 },
									{ text: "Charonite Ogryns", cost: 15 },
								],
							},
						],
					},
				},
				{
					id: 9003,
					type: "Core",
					faction: "Solar Auxillia",
					restricted: true,
					options: [2002],
					description: "Lasrifle detachment",
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4compulsorySlot3",
					selected_unit: {
						id: 2002,
						name: "Auxilia Lasrifle Tercio",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Core",
						base_cost: 30,
						base_size: 4,
						max_size: 16,
						main_unit: [2002],
						related_unit: [9000, 9001],
						loadout: [{ text_option: ["Auxillia lasrifles"] }],
						upgrade_options: [
							{ name: "Additional Auxiliaries", number: 4, cost: 24, size: 4 },
							{ name: "Additional Auxiliaries with Flamers", number: 0, cost: 0, size: 0 },
							{ name: "Additional Veletarii", number: 0, cost: 0, size: 0 },
							{ name: "Additional Charonite Ogryns", number: 0, cost: 0, size: 0 },
						],
						datasheet_info: [
							{
								text: "An Auxilia Lasrifle Tercio can purchase up to six upgrades. It may purchase the same upgrade multiple times: Each upgrade increases the Detachment size by 2.",
								options: [
									{ text: "Auxiliaries", cost: 12 },
									{ text: "Auxiliaries with Flamers", cost: 12 },
									{ text: "Veletarii", cost: 12 },
									{ text: "Charonite Ogryns", cost: 15 },
								],
							},
						],
					},
				},
			],
			optional: [
				{
					id: 2001,
					type: "Core",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot0",
					selected_unit: {
						id: 2002,
						name: "Auxilia Lasrifle Tercio",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Core",
						base_cost: 30,
						base_size: 4,
						max_size: 16,
						main_unit: [2002],
						related_unit: [9000, 9001],
						loadout: [{ text_option: ["Auxillia lasrifles"] }],
						upgrade_options: [
							{ name: "Additional Auxiliaries", number: 4, cost: 24, size: 4 },
							{ name: "Additional Auxiliaries with Flamers", number: 0, cost: 0, size: 0 },
							{ name: "Additional Veletarii", number: 2, cost: 12, size: 2 },
							{ name: "Additional Charonite Ogryns", number: 0, cost: 0, size: 0 },
						],
						datasheet_info: [
							{
								text: "An Auxilia Lasrifle Tercio can purchase up to six upgrades. It may purchase the same upgrade multiple times: Each upgrade increases the Detachment size by 2.",
								options: [
									{ text: "Auxiliaries", cost: 12 },
									{ text: "Auxiliaries with Flamers", cost: 12 },
									{ text: "Veletarii", cost: 12 },
									{ text: "Charonite Ogryns", cost: 15 },
								],
							},
						],
					},
				},
				{
					id: 2002,
					type: "Support",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot1",
					selected_unit: {
						id: 2003,
						name: "Auxilia Ogryn Charonite Section",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Support",
						base_cost: 50,
						base_size: 4,
						max_size: 8,
						main_unit: [2004],
						related_unit: [],
						loadout: [{ text_option: ["Charonite claws"] }],
						upgrade_options: [{ name: "Additional Charonite Ogryn", number: 4, cost: 30, size: 4 }],
						datasheet_info: [
							{
								text: "An Auxilia Charonite Ogryn Section can purchase the following upgrades:",
								options: [
									{ text: "2 additional Charonite Ogryn", cost: 15 },
									{ text: "4 additional Charonite Ogryn", cost: 30 },
								],
							},
						],
					},
				},
				{
					id: 2002,
					type: "Support",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot2",
					selected_unit: {
						id: 2004,
						name: "Auxilia Veletaris Storm Section",
						faction: "Solar Auxillia",
						allegiance: "Neutral",
						detachment_type: "Support",
						base_cost: 40,
						base_size: 4,
						max_size: 8,
						main_unit: [2003],
						related_unit: [],
						loadout: [{ text_option: ["Auxilia laspistols", "Power axes"] }],
						upgrade_options: [{ name: "Additional Veletarii", number: 4, cost: 20, size: 4 }],
						datasheet_info: [
							{
								text: "An Auxilia Veletaris Storm Section can purchase the following upgrades:",
								options: [
									{ text: "2 additional Veletarii", cost: 10 },
									{ text: "4 additional Veletarii", cost: 20 },
								],
							},
						],
					},
				},
				{
					id: 2005,
					type: "Battle Tank",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot3",
					selected_unit: null,
				},
				{
					id: 2010,
					type: "Transport",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot4",
					selected_unit: null,
				},
				{
					id: 2010,
					type: "Transport",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot5",
					selected_unit: null,
				},
				{
					id: 2010,
					type: "Transport",
					faction: "Solar Auxillia",
					options: [],
					ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
					slot_ref: "formation-TJIw_1av4uZqTyh8nQL4optionalSlot6",
					selected_unit: null,
				},
			],
			choice: [
				[
					{
						id: 2003,
						type: "Vanguard",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
						slot_ref: "formation-TJIw_1av4uZqTyh8nQL4choiceSlots00",
						selected_unit: {
							id: 2007,
							name: "Auxilia Aethon Heavy Sentinel Patrol",
							faction: "Solar Auxillia",
							allegiance: "Neutral",
							detachment_type: "Vanguard",
							base_cost: 35,
							base_size: 2,
							max_size: 8,
							main_unit: [2007],
							related_unit: [],
							loadout: [{ text_option: ["Multi-laser", "Sentinel missile launcher"] }],
							upgrade_options: [{ name: "Additional Sentinel", number: 0, cost: 0, size: 0 }],
							datasheet_info: [
								{
									text: "An Auxilia Aethon Heavy Sentinel Patrol can purchase the following upgrades:",
									options: [
										{ text: "2 additional Sentinel", cost: 25 },
										{ text: "4 additional Sentinel", cost: 45 },
										{ text: "6 additional Sentinel", cost: 65 },
									],
								},
							],
						},
					},
					{
						id: 2004,
						type: "Light Armour",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
						slot_ref: "formation-TJIw_1av4uZqTyh8nQL4choiceSlots01",
						selected_unit: null,
					},
				],
				[
					{
						id: 2005,
						type: "Battle Tank",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
						slot_ref: "formation-TJIw_1av4uZqTyh8nQL4choiceSlots10",
						selected_unit: null,
					},
					{
						id: 2007,
						type: "Artillery",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
						slot_ref: "formation-TJIw_1av4uZqTyh8nQL4choiceSlots11",
						selected_unit: null,
					},
					{
						id: 2008,
						type: "Air Support",
						faction: "Solar Auxillia",
						options: [],
						ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
						slot_ref: "formation-TJIw_1av4uZqTyh8nQL4choiceSlots12",
						selected_unit: null,
					},
				],
			],
			ref_id: "formation-TJIw_1av4uZqTyh8nQL4",
		},
		{
			id: 4000,
			name: "Knight Household Lance",
			faction: "Strategic Assets",
			allegiance: "Neutral",
			compulsory: [
				{
					id: 4000,
					type: "Knight",
					faction: "Strategic Assets",
					options: [],
					ref_id: "formationasYMYgbzLWPabR_U4Dkwe",
					slot_ref: "formationasYMYgbzLWPabR_U4DkwecompulsorySlot0",
					selected_unit: {
						id: 4010,
						name: "Cerastus Knight Banner",
						faction: "Strategic Assets",
						allegiance: "Neutral",
						detachment_type: "Knight",
						base_cost: 215,
						base_size: 1,
						max_size: 6,
						break_strength: 3,
						main_unit: [4014],
						related_unit: [4015, 4003, 4004],
						loadout: [
							{
								text: "Each Cerastus Knight has one of the following weapon loadouts:",
								text_option: [
									"Knight Acheron: Acheron pettern flame cannon, Reaper chainfist and in-build twin-linked heavy bolters",
									"Knight Castigator: Castigator pattern bolt cannon and a Tempest Warblade",
									"Knight Lancer: Shock Lance and an Ion gauntlet shield",
								],
							},
							{
								text: "For +20 points, a Cerastus Knight may have one of the following loadouts instead:",
								text_option: ["Cerastus Knight Atrapos"],
							},
							{
								itallic_text:
									"A Knight Lancer exchanges the Ion Shield (4+) special rule for Ion Shield (3+)",
							},
						],
						upgrade_options: [
							{ name: "Additional Knight", number: 2, cost: 390, size: 2, break_strength: 3 },
							{ name: "Atropos upgrade", number: 0, cost: 0, size: 0 },
							{ name: "Armiger Talon", number: 0, cost: 0, size: 0 },
							{ name: "Moriax Talon", number: 0, cost: 0, size: 0 },
						],
						datasheet_info: [
							{
								text: "A Cerastus Knight Banner can purchase one of the following upgrades:",
								options: [
									{ text: "1 additional Knight", cost: 200 },
									{ text: "2 additional Knights", cost: 390 },
								],
							},
							{
								text: "In addition, a Cerastus Knight Banner may purchase one of the following upgrades:",
								options: [
									{ text: "Questoris Knight Armiger Talon", cost: 180 },
									{ text: "Mechanicum Knight Moriax Talon", cost: 200 },
								],
								info: "This upgrade increases the Detachment size by 3",
							},
						],
					},
				},
			],
			optional: null,
			choice: null,
			ref_id: "formationasYMYgbzLWPabR_U4Dkwe",
		},
	],
}
