const sxss = {
	points: 3000,
	list_name: "New List",
	list_id: "zxwcl4sbFUBfkMU9DJZ8X",
	user_id: "",
	main_faction: "Legiones Astartes",
	allegiance: null,
	formations: [
		{
			id: 1000,
			name: "Legion Demi-company",
			faction: "Legiones Astartes",
			subfaction: null,
			allegiance: null,
			formation_slots: [
				{
					slot_type: "compulsory",
					slot: [
						{
							id: 1000,
							type: "HQ",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_compulsory0_0",
							selected_unit: null,
						},
						{
							id: 1001,
							type: "Core",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_compulsory0_1",
							selected_unit: null,
						},
						{
							id: 1001,
							type: "Core",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_compulsory0_2",
							selected_unit: null,
						},
						{
							id: 1002,
							type: "Support",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_compulsory0_3",
							selected_unit: null,
						},
					],
				},
				{
					slot_type: "optional",
					slot: [
						{
							id: 1001,
							type: "Core",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_0",
							selected_unit: null,
						},
						{
							id: 1002,
							type: "Support",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_1",
							selected_unit: null,
						},
						{
							id: 1002,
							type: "Support",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_2",
							selected_unit: null,
						},
						{
							id: 1003,
							type: "Vanguard",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_3",
							selected_unit: null,
						},
						{
							id: 1009,
							type: "Bastion",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_4",
							selected_unit: null,
						},
						{
							id: 1010,
							type: "Transport",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_5",
							selected_unit: null,
						},
						{
							id: 1010,
							type: "Transport",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_6",
							selected_unit: null,
						},
						{
							id: 9000,
							type: "Dedicated",
							faction: "Legiones Astartes",
							restricted: true,
							options: [9000],
							description: "Dedicated transport Rhinos",
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_optional1_7",
							selected_unit: null,
						},
					],
				},
				{
					slot_type: "choice",
					slot: [
						{
							id: 1004,
							type: "Light Armour",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_choice2_0",
							selected_unit: null,
						},
						{
							id: 1008,
							type: "Air Support",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_choice2_1",
							selected_unit: {
								id: 1016,
								name: "Legion Storm Eagle Squadron",
								faction: "Legiones Astartes",
								subfaction: null,
								allegiance: null,
								unique: false,
								detachment_type: "Air Support",
								base_cost: 100,
								base_size: 1,
								max_size: 4,
								main_unit: [1016],
								related_unit: [],
								dataslate_loadout: [
									{
										text_option: [
											"Storm Eagle heavy bolter",
											"Vengeance launcher",
											"Wing Mounted lascannon",
										],
									},
								],
								upgrade_options: [
									{
										name: "Additional Storm Eagle",
										number: 0,
										cost: 0,
										size: 0,
									},
								],
								loadout_options: [],
								datasheet_info: [
									{
										text: "A Legion Storm Eagle Squadron can purchase the following upgrades:",
										options: [
											{
												text: "1 additional Storm Eagle",
												cost: 100,
											},
											{
												text: "2 additional Storm Eagle",
												cost: 190,
											},
										],
									},
								],
							},
						},
					],
				},
				{
					slot_type: "choice",
					slot: [
						{
							id: 1005,
							type: "Battle Tank",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_choice3_0",
							selected_unit: null,
						},
						{
							id: 1006,
							type: "Heavy Armour",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_choice3_1",
							selected_unit: {
								id: 1014,
								name: "Legion Kratos Squadron",
								faction: "Legiones Astartes",
								subfaction: null,
								allegiance: null,
								unique: false,
								detachment_type: "Heavy Armour",
								base_cost: 150,
								base_size: 2,
								max_size: 6,
								main_unit: [1014],
								related_unit: [],
								dataslate_loadout: [
									{
										text_option: [
											"Kratos battlecannon with Co-axial autocannon or Melta blastgun with Co-axial autocannon",
											"Two Hull Mounted heavy bolter or two Kratos lascannon or two Kratos autocannon",
											"Sponson Mounted heavy bolters or Sponson Mounted lascannon",
										],
									},
								],
								upgrade_options: [
									{
										name: "Additional Kratos",
										number: 0,
										cost: 0,
										size: 0,
									},
								],
								loadout_options: [
									{
										location: "Turret",
										options: [
											{
												weapon: "Kratos battlecannon",
												number: 0,
											},
											{
												weapon: "Melta blastgun",
												number: 0,
											},
										],
									},
									{
										location: "Sponson",
										options: [
											{
												weapon: "Heavy bolters",
												number: 0,
											},
											{
												weapon: "Lascannons",
												number: 0,
											},
										],
									},
									{
										location: "Hull",
										options: [
											{
												weapon: "Heavy bolters",
												number: 0,
											},
											{
												weapon: "Lascannons",
												number: 0,
											},
											{
												weapon: "Autocannons",
												number: 0,
											},
										],
									},
								],
								datasheet_info: [
									{
										text: "A Legion Kratos Squadron can purchase the following upgrades: The same upgrade may be taken more than once",
										options: [
											{
												text: "1 additional Kratos",
												cost: 60,
											},
											{
												text: "2 additional Kratos",
												cost: 110,
											},
											{
												text: "4 additional Kratos",
												cost: 200,
											},
										],
									},
								],
							},
						},
						{
							id: 1007,
							type: "Artillery",
							faction: "Legiones Astartes",
							restricted: false,
							options: [],
							ref_id: "JXHypYcMUjLQoaGNKC9z_",
							slot_ref: "JXHypYcMUjLQoaGNKC9z_choice3_2",
							selected_unit: null,
						},
					],
				},
			],
			ref_id: "JXHypYcMUjLQoaGNKC9z_",
		},
	],
}
